subcomponent_config_file: true

export_name: reservoir

enable_execute_command: true

service_namespace: ecs #enables application scaling configuration

cpu:
  Ref: Cpu
memory:
  Ref: Memory

availability_zone_rebalancing: DISABLED

iam_policies:
  ec2-regions:
    action:
      - ec2:DescribeRegions
  ssm-parameters:
    action:
      - ssm:GetParameter
      - ssm:GetParametersByPath

task_definition:
  app:
    image: 210662219476.dkr.ecr.us-east-1.amazonaws.com/boddle-learning/reservoir
    tag_param: Version
    ports:
      - 8080
    env_vars:
      ENV_NAME:
        Fn::Sub: "${EnvironmentName}"
      AWS_REGION:
        Ref: AWS::Region
      ENV_REGION:
        Ref: AWS::Region
      SSM_PATH:
        Fn::Sub: "/boddle/${EnvironmentName}/reservoir"
    ulimits:
      - name: nofile
        softLimit: 65535
        hardLimit: 65535
