subcomponent_config_file: true

export_name: reservoir

enable_execute_command: true

service_namespace: ecs #enables application scaling configuration

cpu: 
  Ref: Cpu
memory:
  Ref: Memory

iam_policies:
  ec2-regions:
    action:
      - ec2:DescribeRegions
  ssm-parameters:
    action:
      - ssm:GetParameter
      - ssm:GetParametersByPath
  s3-content:
    action:
      - '*'
    resource:
      - Fn::Sub: arn:aws:s3:::${EnvironmentName}-${AWS::Region}-content-boddlelearning-com
      - Fn::Sub: arn:aws:s3:::${EnvironmentName}-${AWS::Region}-content-boddlelearning-com/*

task_definition:
  app:
    image: 210662219476.dkr.ecr.us-east-1.amazonaws.com/boddle-learning/reservoir
    tag_param: Version
    ports:
      - 8080
    env_vars:
      APP_NAME: boddle-reservoir
      ENV_NAME:
        Fn::Sub: "${EnvironmentName}"
      ENV_REGION:
        Ref: AWS::Region
      SSM_PATH:
        Fn::Sub: "/boddle/${EnvironmentName}/reservoir"
      

ingress_rules:
  - from: 8080
    source_sg:
      Ref: LoadBalancerSecurityGroup
    desc: allows traffic from ALB

targetgroup:
  name: engine
  type: ip
  container: app
  port: 8080
  protocol: http
  listener: http
  healthcheck:
    path: /health
    code: 200
  attributes:
    deregistration_delay.timeout_seconds: 10
  rules:
    - host: reservoir.*
      priority: 60

scaling_policy:
  target:
    metric_type: ECSServiceAverageCPUUtilization
    scale_in_cooldown: 300
    scale_out_cooldown: 30
    target_value: 60